[workspace]
members = ["corrosive_ecs_core_macro", "corrosive-ecs-core"]

[package]
name = "corrosive-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bus = "2.4.1"
corrosive-ecs-core = {path = "corrosive-ecs-core"}
corrosive_ecs_core_macro = {path = "corrosive_ecs_core_macro"}
rand = "0.9.0-alpha.2"


[build-dependencies]
corrosive-ecs-core = {path = "corrosive-ecs-core" , features = ["build"]}
corrosive_ecs_core_macro = {path = "corrosive_ecs_core_macro", features = ["build"]}
